name: 'px cloud foundry action'
description: 'docker action for handling cloud foundry cmd'
inputs: 
  cf_api:
    description: 'cloud foundry api'
  cf_username:
    description: 'cloud foundry username'
  cf_password:
  cf_org:
  cf_space:
