name: 'px cloud foundry action'
description: 'docker action for handling cloud foundry cmd'
inputs: 
  cf_api:
    description: 'cloud foundry api'
    required: true
  cf_username:
    description: 'cloud foundry username'
    required: true
  cf_password:
    description: 'cloud foundry password'
    required: true
  cf_org:
    description: 'cloud foundry organisation'
     required: true
  cf_space:
    description: 'cloud foundry space'
    required: true
    
runs:
  using: 'docker'
  image: 'DockerFile'
    env:
      CF_API: ${{ inputs.cf_api }}
      CF_USERNAME: ${{ inputs.cf_username }}
      CF_PASSWORD: ${{ inputs.cf_password }}
      CF_ORG: ${{ inputs.cf_org }}
      CF_SPACE: ${{ inputs.cf_space }}
