name: 'px cloud foundry action'
description: 'docker action for handling cloud foundry cmd'
branding:
  icon: "share"
  color: "purple"
inputs: 
  cf_api:
    description: 'cloud foundry api'
    required: true
  cf_username:
    description: 'cloud foundry username'
    required: true
  cf_password:
    description: 'cloud foundry password'
    required: true
  cf_org:
    description: 'cloud foundry organisation'
     required: true
  cf_space:
    description: 'cloud foundry space'
    required: true
  command:
    description: "Command to run using CF CLI eg: cf push"
    required: true
  
    
runs:
  using: 'docker'
  image: 'DockerFile'
   args:
    - ${{ inputs.command }}
